/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OfficeListRouteImport } from './routes/office-list'
import { Route as IndiaSriLankaEconomicAndTradeEngagementRouteImport } from './routes/india-sri-lanka-economic-and-trade-engagement'
import { Route as IndiaSriLankaBilateralRelationsRouteImport } from './routes/india-sri-lanka-bilateral-relations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsulGeneralRouteImport } from './routes/consul-general'
import { Route as IndexRouteImport } from './routes/index'

const OfficeListRoute = OfficeListRouteImport.update({
  id: '/office-list',
  path: '/office-list',
  getParentRoute: () => rootRouteImport,
} as any)
const IndiaSriLankaEconomicAndTradeEngagementRoute =
  IndiaSriLankaEconomicAndTradeEngagementRouteImport.update({
    id: '/india-sri-lanka-economic-and-trade-engagement',
    path: '/india-sri-lanka-economic-and-trade-engagement',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndiaSriLankaBilateralRelationsRoute =
  IndiaSriLankaBilateralRelationsRouteImport.update({
    id: '/india-sri-lanka-bilateral-relations',
    path: '/india-sri-lanka-bilateral-relations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsulGeneralRoute = ConsulGeneralRouteImport.update({
  id: '/consul-general',
  path: '/consul-general',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consul-general': typeof ConsulGeneralRoute
  '/contact': typeof ContactRoute
  '/india-sri-lanka-bilateral-relations': typeof IndiaSriLankaBilateralRelationsRoute
  '/india-sri-lanka-economic-and-trade-engagement': typeof IndiaSriLankaEconomicAndTradeEngagementRoute
  '/office-list': typeof OfficeListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consul-general': typeof ConsulGeneralRoute
  '/contact': typeof ContactRoute
  '/india-sri-lanka-bilateral-relations': typeof IndiaSriLankaBilateralRelationsRoute
  '/india-sri-lanka-economic-and-trade-engagement': typeof IndiaSriLankaEconomicAndTradeEngagementRoute
  '/office-list': typeof OfficeListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consul-general': typeof ConsulGeneralRoute
  '/contact': typeof ContactRoute
  '/india-sri-lanka-bilateral-relations': typeof IndiaSriLankaBilateralRelationsRoute
  '/india-sri-lanka-economic-and-trade-engagement': typeof IndiaSriLankaEconomicAndTradeEngagementRoute
  '/office-list': typeof OfficeListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consul-general'
    | '/contact'
    | '/india-sri-lanka-bilateral-relations'
    | '/india-sri-lanka-economic-and-trade-engagement'
    | '/office-list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consul-general'
    | '/contact'
    | '/india-sri-lanka-bilateral-relations'
    | '/india-sri-lanka-economic-and-trade-engagement'
    | '/office-list'
  id:
    | '__root__'
    | '/'
    | '/consul-general'
    | '/contact'
    | '/india-sri-lanka-bilateral-relations'
    | '/india-sri-lanka-economic-and-trade-engagement'
    | '/office-list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsulGeneralRoute: typeof ConsulGeneralRoute
  ContactRoute: typeof ContactRoute
  IndiaSriLankaBilateralRelationsRoute: typeof IndiaSriLankaBilateralRelationsRoute
  IndiaSriLankaEconomicAndTradeEngagementRoute: typeof IndiaSriLankaEconomicAndTradeEngagementRoute
  OfficeListRoute: typeof OfficeListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/office-list': {
      id: '/office-list'
      path: '/office-list'
      fullPath: '/office-list'
      preLoaderRoute: typeof OfficeListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/india-sri-lanka-economic-and-trade-engagement': {
      id: '/india-sri-lanka-economic-and-trade-engagement'
      path: '/india-sri-lanka-economic-and-trade-engagement'
      fullPath: '/india-sri-lanka-economic-and-trade-engagement'
      preLoaderRoute: typeof IndiaSriLankaEconomicAndTradeEngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/india-sri-lanka-bilateral-relations': {
      id: '/india-sri-lanka-bilateral-relations'
      path: '/india-sri-lanka-bilateral-relations'
      fullPath: '/india-sri-lanka-bilateral-relations'
      preLoaderRoute: typeof IndiaSriLankaBilateralRelationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consul-general': {
      id: '/consul-general'
      path: '/consul-general'
      fullPath: '/consul-general'
      preLoaderRoute: typeof ConsulGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsulGeneralRoute: ConsulGeneralRoute,
  ContactRoute: ContactRoute,
  IndiaSriLankaBilateralRelationsRoute: IndiaSriLankaBilateralRelationsRoute,
  IndiaSriLankaEconomicAndTradeEngagementRoute:
    IndiaSriLankaEconomicAndTradeEngagementRoute,
  OfficeListRoute: OfficeListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
